-- Create table using create query
CREATE TABLE cookies_sales (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cookie_name VARCHAR(100),
    manufacturer VARCHAR(100),
    sales INT
);

-- Insert the sample data 
INSERT INTO cookies_sales (cookie_name, manufacturer, sales) VALUES
('Chocolate Chip Cookies', 'ABC Bakery', 40000),
('Oatmeal Raisin Cookies', 'XYZ Confections', 70000),
('Sugar Cookies', 'PQR Sweets', 60000),
('Peanut Butter Cookies', 'LMN Bakes', 50000),
('Snickerdoodle Cookies', 'NOP Treats', 40000),
('Shortbread Cookies', 'QRS Pastries', 45000),
('Macadamia Nut Cookies', 'STU Desserts', 50000),
('Gingerbread Cookies', 'VWX Delights', 35000),
('White Chocolate Macadamia Nut Cookies', 'RST Bakery', 25000),
('Double Chocolate Cookies', 'MNO Confections', 30000),
('Lemon Cookies', 'GHI Sweets', 40000),
('Almond Cookies', 'JKL Bakes', 50000),
('Butter Cookies', 'EFG Treats', 45000),
('Coconut Cookies', 'HIJ Pastries', 40000),
('Cinnamon Cookies', 'OPQ Desserts', 30000),
('Raspberry Thumbprint Cookies', 'KLM Delights', 35000),
('Pistachio Cookies', 'UVW Bakery', 50000),
('M&M Cookies', 'ABC Confections', 50000),
('Cranberry Orange Cookies', 'XYZ Sweets', 45000),
('Maple Pecan Cookies', 'PQR Bakes', 25000),
('Espresso Cookies', 'LMN Treats', 20000),
('Red Velvet Cookies', 'NOP Pastries', 40000),
('Toffee Cookies', 'QRS Desserts', 45000),
('Pumpkin Cookies', 'STU Delights', 30000),
('Coconut Macaroons', 'VWX Bakery', 25000),
('Cherry Chocolate Chip Cookies', 'RST Confections', 20000),
('Peanut Butter Blossom Cookies', 'MNO Sweets', 35000),
('Salted Caramel Cookies', 'GHI Bakes', 40000),
('Lavender Shortbread Cookies', 'JKL Treats', 45000),
('Matcha Green Tea Cookies', 'EFG Pastries', 40000),
('S mores Cookies', 'HIJ Desserts', 35000),
('Pecan Sandies', 'OPQ Delights', 30000),
('Coconut Lime Cookies', 'KLM Bakery', 35000),
('Brown Butter Cookies', 'UVW Confections', 40000),
('Almond Joy Cookies', 'ABC Sweets', 30000),
('Funfetti Cookies', 'XYZ Bakes', 45000),
('Rosemary Olive Oil Cookies', 'PQR Treats', 25000),
('Black and White Cookies', 'LMN Pastries', 20000),
('Chai Spiced Cookies', 'NOP Desserts', 35000),
('Caramel Apple Cookies', 'QRS Delights', 40000),
('Lemon Blueberry Cookies', 'RST Sweets', 25000),
('Pumpkin Spice Cookies', 'MNO Bakes', 20000),
('Gingersnap Cookies', 'GHI Treats', 35000),
('Key Lime Cookies', 'JKL Pastries', 40000),
('Pistachio Rosewater Cookies', 'EFG Desserts', 45000),
('Cranberry White Chocolate Cookies', 'HIJ Delights', 30000),
('Tiramisu Cookies', 'OPQ Bakery', 25000);